In [20]:
import pandas as pd
def mensagem(mensagem):
  print(mensagem)
def vazio():
  print()

df = pd.read_csv("https://raw.githubusercontent.com/Projetar-Solucoes/materiais-trilha/main/semana-04/solicitacoes_semana4.csv")
mensagem('Visualizar Primeiras 5 Linhas')
display(df.head()) #visualiza primeiras 5 linhas
vazio()

mensagem("Mostrar Quantas Linhas/Colunas")
display(df.shape) #mostra quantas (linhas,colunas)
vazio()

mensagem("Como o Pandas Interpreta cada Dado em cada Coluna")
display(df.dtypes) #como o pandas interpreta cada dado
vazio()

mensagem("Calcula Quantas Colunas Vazias tem pelo .isna retornando True ou False, e o .sum somando os True")
display(df.isna().sum()) #isna retorna True ou False se está vazio, sum soma aqueles True vazio
vazio()

mensagem('Calcula Quantas Linhas Repetidas Tem pelo .duplicated retornando True ou False, e o .sum somando os True')
display(df.duplicated().sum()) #duplicated verifica repetidos, retorna True ou False, e o sum soma os True duplicado
vazio()

mensagem('Mostra as Estatísticas da Categoria e soma-as pelo .value_counts')
print(df["categoria"].value_counts())
vazio()

mensagem("Mostra as Estatísticas da Prioridade e soma-as pelo .value_counts")
print(df["prioridade"].value_counts())
vazio()

mensagem("Mostra as Estatísticas do Status e soma-as pelo .value_counts")
print(df["status"].value_counts())
vazio()

mensagem("Mostra as Estatísticas da Unidade e soma-as pelo .value_counts")
print(df["unidade"].value_counts())
vazio()

Visualizar Primeiras 5 Linhas

,protocolo,data_abertura,solicitante,setor,categoria,assunto,prioridade,status,data_fechamento,avaliacao,unidade
0,2026-0173,2026-09-26,Bruno Nunes,Atendimento,Suporte de TI,Impressora sem conexão,Média,Aberta,NaN,NaN,Parambu
1,2026-0053,2026-08-31,Marta Dias,Comercial,ACESSO,Acesso ao sistema de ponto,Média,Concluída,2026-09-03,4.0,Parambu
2,2026-0238,2026-09-06,Nilo Barros,Operações,dúvida,Horário do plantão,Baixa,Concluída,2026-09-06,3.0,Solonópole
3,2026-0103,2026-08-31,Bruno Barros,RH,Suporte TI,Impressora sem conexão,Alta,Concluída,2026-09-15,4.0,Parambu
4,2026-0013,18/08/2026,Sérgio Alves,RH,Infraestrutura,Cadeira quebrada,Alta,Aberta,NaN,NaN,Parambu

Mostrar Quantas Linhas/Colunas

(246, 11)

Como o Pandas Interpreta cada Dado em cada Coluna

protocolo           object
data_abertura       object
solicitante         object
setor               object
categoria           object
assunto             object
prioridade          object
status              object
data_fechamento     object
avaliacao          float64
unidade             object
dtype: object

Calcula Quantas Colunas Vazias tem pelo .isna retornando True ou False, e o .sum somando os True

protocolo            0
data_abertura        0
solicitante          0
setor               10
categoria            0
assunto              0
prioridade          14
status               0
data_fechamento    111
avaliacao          122
unidade              0
dtype: int64

Calcula Quantas Linhas Repetidas Tem pelo .duplicated retornando True ou False, e o .sum somando os True

np.int64(6)

Mostra as Estatísticas da Categoria e soma-as pelo .value_counts
categoria
Financeiro        31
infraestrutura    20
Duvida            20
acesso            18
Infra             17
Infraestrutura    17
Dúvida            17
ACESSO            16
Suporte TI        16
dúvida            16
financeiro        16
Acesso            14
 Suporte TI       12
Suporte de TI      9
suporte ti         7
Name: count, dtype: int64

Mostra as Estatísticas da Prioridade e soma-as pelo .value_counts
prioridade
Média      90
Baixa      70
Alta       40
Urgente    21
BAIXA       5
MÉDIA       3
ALTA        2
URGENTE     1
Name: count, dtype: int64

Mostra as Estatísticas do Status e soma-as pelo .value_counts
status
Concluída       132
Em andamento     45
Aberta           30
Cancelada        28
em andamento      4
cancelada         4
concluída         3
Name: count, dtype: int64

Mostra as Estatísticas da Unidade e soma-as pelo .value_counts
unidade
Parambu       123
Solonópole    123
Name: count, dtype: int64